# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc8778779679444834e61492c7c94cee05a50bc74ad2a073721b5aca94477b592ae9ae1f042e0fc5afcdf0ce6024ec8d50d3795e706d80c7d038d4c6614e91a

test:
  secret_key_base: 4d6a7046a2e8d98bef4fb529c8ed37d0fda2fc163e3d8332379148445f655029983c6f68a49912eaa7ee5582b3eec4c0e7c55c25b51c7457771b949075237926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
